travis:
  secure:
    BINSTAR_TOKEN: LPxOc+xACyKBYhSYUPhMlzQ+ZY0nE1baQ06JfmPjgqaN4r9L7cf66zlvK3R+RCet2Y35QfMqWpk0y77AGS9Ft7TzYJGAtNXWRJYnW7lWBuRIfBmekW2L/kdioeLHoMGZev4e4a7oZuUB37MRSG11IKAjRtMRQ5Y287O17esN1WyucySf1feyQoeyO+KQZm64CH0mnlMW+Xy38+h/Yr8nv4iRZYFRxTBbkhsrjBHfo9ylDALEkNq2Abq05HN7Jk6nvYczmAen1p3Vh+DmNTU24/ibKlTsJjW7yiN2phclqI5eYj9lMZt4RQMCs95sKeGhLZC+QzhzUQoTQtZu06ng0DBAhf86d35lDHhbqMv8S39EM/OU2BhOE0TgE6fm1HzfDcBBmDX6oM/ZnfFjqynmlZuv/0G1tXB8Rrh1gm5J9amh1KN5vKe7ZR2lILmjCAXCzsRvB/pRwAq7o9Wq8rbfGS9k5QJ3dpbOZGiNRL+qCwqCJvtCRjemTL0FMycfvUfbr3afWVveM8VrUNBHaPlCFkDEP3gVU6fAXu4mCkFqOkzKj4WVpKg4uar+vwByQXWt9vkE3Z6mTcg1iSB+p+Eghj8DLBbUH9jDZSiYJpd23btXD+E9Qp5Qb8GTJ9jJ8BZmdu3b0U4G3aJoEP/S2M4J7jzFXXKZ0q6ThTNJUvXpfcs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
